# Goal
float64 traj_duration
float64 acc_duration
float64 total_time
float64 trajectory_len
float64 kp
float64[3] end_position

---
# Result
float64 final_error_norm

---
# Feedback
float64 error_norm